#!/usr/bin/env python3
"""
Alchemy Auth Setup
==================
Interactive one-time helper to generate secure authentication credentials.

Run once before first launch:
    python scripts/setup_auth.py

Outputs the four lines to paste into your .env file, and prints the QR code
URL to add to Google Authenticator / Authy.
"""

import sys
import getpass

sys.path.insert(0, ".")

from src.auth.auth_manager import AuthManager


def main():
    print("\n" + "=" * 60)
    print("  ALCHEMY — Authentication Setup")
    print("=" * 60 + "\n")

    # Username
    username = input("Admin username [admin]: ").strip() or "admin"

    # Password
    while True:
        pw = getpass.getpass("Admin password: ")
        pw2 = getpass.getpass("Confirm password: ")
        if pw == pw2 and len(pw) >= 8:
            break
        if pw != pw2:
            print("  ✗ Passwords do not match. Try again.\n")
        else:
            print("  ✗ Password must be at least 8 characters.\n")

    # Generate secrets
    password_hash = AuthManager.hash_password(pw)
    totp_secret = AuthManager.generate_totp_secret()
    jwt_secret = AuthManager.generate_jwt_secret()

    # Show TOTP URI for authenticator app
    mgr = AuthManager(
        secret_key=jwt_secret,
        username=username,
        password_hash=password_hash,
        totp_secret=totp_secret,
    )
    uri = mgr.get_totp_provisioning_uri()

    print("\n" + "=" * 60)
    print("  Add these lines to your .env file:")
    print("=" * 60)
    print("\nAUTH_ENABLED=true")
    print(f"AUTH_USERNAME={username}")
    print(f"AUTH_PASSWORD_HASH={password_hash}")
    print(f"JWT_SECRET_KEY={jwt_secret}")
    print(f"TOTP_SECRET={totp_secret}\n")

    print("=" * 60)
    print("  Scan this URI with Google Authenticator / Authy:")
    print("=" * 60)
    print(f"\n{uri}\n")
    print("Or open GET /api/auth/setup in your browser after starting the")
    print("server to see the QR code image.\n")

    # Optionally write to .env
    write = input("Append to .env automatically? [y/N]: ").strip().lower()
    if write == "y":
        with open(".env", "a") as f:
            f.write("\n# ── Auth (generated by scripts/setup_auth.py) ──────────────\n")
            f.write("AUTH_ENABLED=true\n")
            f.write(f"AUTH_USERNAME={username}\n")
            f.write(f"AUTH_PASSWORD_HASH={password_hash}\n")
            f.write(f"JWT_SECRET_KEY={jwt_secret}\n")
            f.write(f"TOTP_SECRET={totp_secret}\n")
        print("  ✓ Credentials appended to .env")
    print("\nSetup complete. Restart the server to apply changes.\n")


if __name__ == "__main__":
    main()
